version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerize app
          command: |
            ./.circleci/dockerize.sh
